### ISSUE TITLE
As a user, I want a daily budget reports sent to my email inbox

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/monitoring#14]
### Checked for duplicates

No - I haven't checked

### 🧑‍🔬 User Persona(s)

Node Resource Analyst

### 💪 Motivation

...so that I can monitor costs over time.

### 📖 Additional Details

Create new email list pdsen-cloud-budget@jpl.nasa.gov. Open to other email list ideas. We will have similar emails lists for all external partners (e.g. pdssbn-cloud-budget@jpl.nasa.gov)

### Acceptance Criteria

**Given** a day
**When I perform** opening my email
**Then I expect** to receive a budget report from AWS sometime during that day

**Comment by viviant100** [comment]
Access denied when creating anomaly monitoring (GSD-3602)

**Comment by jordanpadams** [comment]
@viviant100 from an account by account basis, this appears to be working, no? This looks to just be broken from the Kion perspective.

**Comment by viviant100** [comment]
@jordanpadams yes, it's sending out the daily report.  Just need moderator to distribute it daily -  A nuisance,  will follow up with SA to see if we remove the distribution step.

**Comment by jordanpadams** [comment]
@viviant100 I removed that from the distribution list options so it should just work now. I think it’s just tied to who can send emails to that email list, and i’m OK with getting spam if it means I don’t have to moderate.

**Comment by viviant100** [comment]
this is done late June/early July.
