### ISSUE TITLE
Setup email notifications for continuous monitoring

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/monitoring#19]
### 💡 Description

-  Configure JPL SMTP
- Send to PDS SA, Dev, and Ops email lists

**Comment by nutjob4life** [comment]
"Service" or "application" account request made; currently tracked in JPL JRA ICAM-18665

**Comment by nutjob4life** [comment]
The application account `pdsen-orbit@jpl.nasa.gov` has been created. The password needs to be set by a member of `pdsen-ops` by visiting `dir/ai` with a browser

The username and password should be then tested with JPL SMTP, such as with [the Python SMTP client](https://docs.python.org/3/library/smtplib.html), as sometimes application accounts need further "poking/prodding" to get them to work with JPL SMTP.

Once confirmed, the secrets in https://github.com/NASA-PDS/PlanetPatrol/settings/secrets/actions will need to be updated as follows:

- NOTIFICATION_EMAIL_SMTP_USERNAME = pdsen-orbit@jpl.nasa.gov
- NOTIFICATION_EMAIL_SMTP_PASSWORD = the password set by a member of `pdsen-ops`

**Comment by jordanpadams** [comment]
@nutjob4life secrets updated... sorry I missed the testing part :-/

**Comment by nutjob4life** [comment]
@jordanpadams I got you fam, testing now

Okay, test doesn't work. The application account apparently lacks smtp permissions. I've filed INC0590116 to request that smtp access be given

(You'd think that'd be automatic given that the description of the account that they literally put in is: "Used for the Engineering Node of the PDS in order to authenticate with **SMTP** and other JPL resources" 🙄)

**Comment by nutjob4life** [comment]
Update: made argument with Kevin Reelfs (JPL Postmaster) on reasons to enable SMTP access for the account on 2024-07-17 … no response yet

**Comment by nutjob4life** [comment]
Update: Kevin Reelfs reached out to the appropriate department and enabled SMTP access for our "application" account.

Tested with the following script:
```python
import smtplib

user = 'REDACTED@jpl.nasa.gov'
pwd = 'EVEN-MORE-REDACTED'

with smtplib.SMTP(host='ALSO-REDACTED-BUT-EASILY-GUESSED.jpl.nasa.gov', port=587) as s:
    s.starttls()
    s.login(user, pwd)
```

Now that they work [I also updated the secrets in PlanetPatrol](https://github.com/NASA-PDS/PlanetPatrol/settings/secrets/actions).

**Comment by jordanpadams** [comment]
Updated this to only email to our Ops account to quiet the noise a bit.
